name: "Docs Check"
on:
  pull_request:
  push:
    branches:
      - $ros_distro$
  schedule:
    # Run every week to detect flakiness and broken dependencies
    - cron: "0 0 * * 0"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: ros-controls/control.ros.org-deployment-scripts@master
      with:
        install_extensions: false
